# This file was generated by GoReleaser. DO NOT EDIT.
class Synodeploy < Formula
  desc "Deploy containers to Synology DSM 7.2+ with ease"
  homepage "https://github.com/scttfrdmn/syno-docker"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/syno-docker/releases/download/v0.1.1/syno-docker-Darwin-x86_64.tar.gz"
      sha256 "PLACEHOLDER_INTEL_MAC_SHA256"

      def install
        bin.install "syno-docker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/syno-docker/releases/download/v0.1.1/syno-docker-Darwin-arm64.tar.gz"
      sha256 "PLACEHOLDER_ARM_MAC_SHA256"

      def install
        bin.install "syno-docker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/syno-docker/releases/download/v0.1.1/syno-docker-Linux-x86_64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_INTEL_SHA256"

      def install
        bin.install "syno-docker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/syno-docker/releases/download/v0.1.1/syno-docker-Linux-arm64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_ARM_SHA256"

      def install
        bin.install "syno-docker"
      end
    end
  end

  def install
    bin.install "syno-docker"

    # Generate shell completions
    output = Utils.safe_popen_read("#{bin}/syno-docker", "completion", "bash")
    (bash_completion/"syno-docker").write output
    output = Utils.safe_popen_read("#{bin}/syno-docker", "completion", "zsh")
    (zsh_completion/"_syno-docker").write output
    output = Utils.safe_popen_read("#{bin}/syno-docker", "completion", "fish")
    (fish_completion/"syno-docker.fish").write output
  end

  test do
    system "#{bin}/syno-docker", "--version"
    system "#{bin}/syno-docker", "--help"
    # Test init command without actually connecting
    output = shell_output("#{bin}/syno-docker init --help")
    assert_match "Setup connection to Synology NAS", output
  end
end